version: "3.7"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: online_judge
    ports:
      - 3306:3306
    volumes:
      - online_judge_mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 80:80

  proxy:
    build: ./proxy
    ports:
      - 7777:7777

volumes:
  online_judge_mysql_data:
