apiVersion: v1
kind: Service
metadata:
  name: online-judge-backend
spec:
  type: NodePort
  selector:
    app: online-judge-backend
  ports:
    - name: http
      port: 80
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-judge-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: online-judge-backend
  template:
    metadata:
      labels:
        app: online-judge-backend
    spec:
      containers:
        - name: online-judge-backend
          image: alvinpiter/online-judge-backend
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: online-judge-backend-configmap
            - secretRef:
                name: online-judge-backend-secret
