apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: online-judge
  annotations:
    kubernetes.io/ingress.global-static-ip-name: online-judge-api
  labels:
    app: online-judge
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: online-judge-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: online-judge-frontend
                port:
                  number: 80
